title: Idealsense
description: Public documentation for Idealsense.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Docs GitHub repository: https://github.com/IdealAQ/public_docs
